#!/bin/bash
echo "Downloading trace Radius Back End SQL Server" 1>&2
cookies=/tmp/cookie$$
cat > $cookies << 'EOF'
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by iotta.snia.org! Edit at your own risk.

iotta.snia.org	FALSE	/	FALSE	0	infodigest	12dde788bf27f320a48a28b16b7988b837a3b913
iotta.snia.org	FALSE	/	FALSE	0	legal	true
iotta.snia.org	FALSE	/	FALSE	0	id	336431
EOF

function useWGET {
  wget --load-cookies=$cookies \
    -O 'RadiusBackEndSQLServer.zip' -c 'http://iotta.snia.org/traces/182/download?type=file&sType=wget'
}
function useCURL {
  curl -b $cookies -o \
    'RadiusBackEndSQLServer.zip' -C - -L 'http://iotta.snia.org/traces/182/download?type=file&sType=curl'
}

if which wget >/dev/null 2>&1; then
  useWGET
elif which curl >/dev/null 2>&1; then
  useCURL
else
  echo "Couldn't find either wget or curl. Please install one of them" 1>&2
fi

rm -f $cookies
